nameOverride: ""
fullnameOverride: ""

# Global/common labels & annotations
commonLabels: {}
commonAnnotations: {}

# Pod-level extra labels/annotations applied to all pods
podLabels: {}
podAnnotations: {}

# --- Image (top-level; was under server) ---
image:
  repository: ghcr.io/lldap/lldap
  # tag defaults to .Chart.AppVersion via helper; override here if needed
  tag: ""
  pullPolicy: IfNotPresent

# --- ServiceAccount (top-level; was under server) ---
serviceAccount:
  create: false
  name: ""

# --- Workload sizing / storage (top-level; was under server) ---
replicaCount: 1

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 8Gi
  storageClass: ""

# --- Resources & security (top-level; was under server) ---
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true

# --- Service (top-level; was under server) ---
service:
  name: ""         # defaults to <release>-lldap-server
  type: ClusterIP
  ldapPort: 389    # maps to container 3890
  ldapsPort: 636   # maps to container 6360
  httpPort: 80     # maps to container 17170
  annotations: {}

# --- LLDAP runtime config (top-level; was under server) ---
lldap:
  baseDN: "dc=example,dc=com"
  adminUsername: "admin"      # short name, not DN
  existingSecret: ""          # provide to manage creds externally
  secrets:
    adminPassword: ""         # autogenerated & retained if empty
    jwtSecret: ""             # autogenerated & retained if empty
    keySeed: ""               # autogenerated & retained if empty

# --- LDAPS options (top-level; was under server) ---
ldaps:
  enabled: false
  existingSecret: ""          # secret with tls.crt / tls.key
  certKey: tls.crt
  keyKey: tls.key

# Extra env for main container (top-level; was under server)
extraEnv: []
# - name: RUST_LOG
#   value: info

# Component-scoped labels/annotations remain namespaced under "server"
server:
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: lldap.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # - secretName: lldap-web-tls
  #   hosts: [lldap.example.com]

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}

networkPolicy:
  enabled: true
  ingressNamespaces: [] # allow from these namespaces, empty allows all

pdb:
  enabled: true
  minAvailable: 1

bootstrap:
  enabled: true
  cleanup: true     # prune entries not in config
  # Line-delimited JSON objects (not an array) required by /app/bootstrap.sh
  users: |
    {"id":"admin","email":"admin@example.com","password":"change-me","displayName":"Admin User","firstName":"Admin","lastName":"User","groups":["ops:admin"]}
  groups: |
    {"name":"ops:admin"}
