name: Validate Charts
on:
  pull_request:
    paths: ['charts/**']

jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.3

      - name: Run helm lint on changed charts
        shell: bash
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          set -euo pipefail

          # List changed files under charts/ between base and head
          mapfile -t CHANGED < <(git diff --name-only "$BASE_SHA...$HEAD_SHA" -- 'charts/*' || true)

          # If nothing changed under charts/, exit early
          if [[ "${#CHANGED[@]}" -eq 0 ]]; then
            echo "No chart changes detected."
            exit 0
          fi

          # Collect unique chart roots (dirs containing Chart.yaml)
          declare -A ROOTS=()
          for f in "${CHANGED[@]}"; do
            d="$f"
            while [[ -n "$d" && "$d" != "." ]]; do
              if [[ -f "$d/Chart.yaml" ]]; then
                ROOTS["$d"]=1
                break
              fi
              d="$(dirname "$d")"
            done
          done

          if [[ "${#ROOTS[@]}" -eq 0 ]]; then
            echo "No Chart.yaml found for changed files. Nothing to lint."
            exit 0
          fi

          # Lint each changed chart (update deps first, but don't fail if none)
          for r in "${!ROOTS[@]}"; do
            echo "::group::helm lint $r"
            helm dependency update "$r" || true
            helm lint "$r"
            echo "::endgroup::"
          done
